using System.Collections.Generic;

namespace IdSharp.Tagging.ID3v2
{
    /// <summary>
    /// Static helper class for ISO-639-2 languages.
    /// </summary>
    public static class LanguageHelper
    {
        /// <summary>
        /// Gets a dictionary containing 3-letter ISO-639-2 language codes as the key and the English version of the language name as the value.
        /// </summary>
        /// <value>A dictionary containing 3-letter ISO-639-2 language codes as the key and the English version of the language name as the value.</value>
        public static Dictionary<string, string> Languages { get; } = new()
        {
            #region <<< Language code / English description dictionary
            { "aar", "Afar" },
            { "abk", "Abkhazian" },
            { "ace", "Achinese" },
            { "ach", "Acoli" },
            { "ada", "Adangme" },
            { "afa", "Afro-Asiatic (Other)" },
            { "afh", "Afrihili" },
            { "afr", "Afrikaans" },
            { "aka", "Akan" },
            { "akk", "Akkadian" },
            { "alb", "Albanian" },
            { "ale", "Aleut" },
            { "alg", "Algonquian Languages" },
            { "amh", "Amharic" },
            { "ang", "English, Old (ca. 450-1100)" },
            { "apa", "Apache Languages" },
            { "ara", "Arabic" },
            { "arc", "Aramaic" },
            { "arm", "Armenian" },
            { "arn", "Araucanian" },
            { "arp", "Arapaho" },
            { "art", "Artificial (Other)" },
            { "arw", "Arawak" },
            { "asm", "Assamese" },
            { "ath", "Athapascan Languages" },
            { "ava", "Avaric" },
            { "ave", "Avestan" },
            { "awa", "Awadhi" },
            { "aym", "Aymara" },
            { "aze", "Azerbaijani" },
            { "bad", "Banda" },
            { "bai", "Bamileke Languages" },
            { "bak", "Bashkir" },
            { "bal", "Baluchi" },
            { "bam", "Bambara" },
            { "ban", "Balinese" },
            { "baq", "Basque" },
            { "bas", "Basa" },
            { "bat", "Baltic (Other)" },
            { "bej", "Beja" },
            { "bel", "Byelorussian" },
            { "bem", "Bemba" },
            { "ben", "Bengali" },
            { "ber", "Berber (Other)" },
            { "bho", "Bhojpuri" },
            { "bih", "Bihari" },
            { "bik", "Bikol" },
            { "bin", "Bini" },
            { "bis", "Bislama" },
            { "bla", "Siksika" },
            { "bnt", "Bantu (Other)" },
            { "bod", "Tibetan" },
            { "bra", "Braj" },
            { "bre", "Breton" },
            { "bua", "Buriat" },
            { "bug", "Buginese" },
            { "bul", "Bulgarian" },
            { "bur", "Burmese" },
            { "cad", "Caddo" },
            { "cai", "Central American Indian (Other)" },
            { "car", "Carib" },
            { "cat", "Catalan" },
            { "cau", "Caucasian (Other)" },
            { "ceb", "Cebuano" },
            { "cel", "Celtic (Other)" },
            { "ces", "Czech" },
            { "cha", "Chamorro" },
            { "chb", "Chibcha" },
            { "che", "Chechen" },
            { "chg", "Chagatai" },
            { "chi", "Chinese" },
            { "chm", "Mari" },
            { "chn", "Chinook jargon" },
            { "cho", "Choctaw" },
            { "chr", "Cherokee" },
            { "chu", "Church Slavic" },
            { "chv", "Chuvash" },
            { "chy", "Cheyenne" },
            { "cop", "Coptic" },
            { "cor", "Cornish" },
            { "cos", "Corsican" },
            { "cpe", "Creoles and Pidgins, English-based (Other)" },
            { "cpf", "Creoles and Pidgins, French-based (Other)" },
            { "cpp", "Creoles and Pidgins, Portuguese-based (Other)" },
            { "cre", "Cree" },
            { "crp", "Creoles and Pidgins (Other)" },
            { "cus", "Cushitic (Other)" },
            { "cym", "Welsh" },
            { "cze", "Czech" },
            { "dak", "Dakota" },
            { "dan", "Danish" },
            { "del", "Delaware" },
            { "deu", "German" },
            { "din", "Dinka" },
            { "div", "Divehi" },
            { "doi", "Dogri" },
            { "dra", "Dravidian (Other)" },
            { "dua", "Duala" },
            { "dum", "Dutch, Middle (ca. 1050-1350)" },
            { "dut", "Dutch" },
            { "dyu", "Dyula" },
            { "dzo", "Dzongkha" },
            { "efi", "Efik" },
            { "egy", "Egyptian (Ancient)" },
            { "eka", "Ekajuk" },
            { "ell", "Greek" },
            { "elx", "Elamite" },
            { "eng", "English" },
            { "enm", "Middle English (ca. 1100-1500)" },
            { "epo", "Esperanto" },
            { "esk", "Eskimo (Other)" },
            { "esl", "Spanish" },
            { "est", "Estonian" },
            { "eus", "Basque" },
            { "ewe", "Ewe" },
            { "ewo", "Ewondo" },
            { "fan", "Fang" },
            { "fao", "Faroese" },
            { "fas", "Persian" },
            { "fat", "Fanti" },
            { "fij", "Fijian" },
            { "fin", "Finnish" },
            { "fiu", "Finno-Ugrian (Other)" },
            { "fon", "Fon" },
            { "fra", "French" },
            { "fre", "French" },
            { "frm", "French, Middle (ca. 1400-1600)" },
            { "fro", "French, Old (842- ca. 1400)" },
            { "fry", "Frisian" },
            { "ful", "Fulah" },
            { "gaa", "Ga" },
            { "gae", "Gaelic (Scots)" },
            { "gai", "Irish" },
            { "gay", "Gayo" },
            { "gdh", "Gaelic (Scots)" },
            { "gem", "Germanic (Other)" },
            { "geo", "Georgian" },
            { "ger", "German" },
            { "gez", "Geez" },
            { "gil", "Gilbertese" },
            { "glg", "Gallegan" },
            { "gmh", "German, Middle High (ca. 1050-1500)" },
            { "goh", "German, Old High (ca. 750-1050)" },
            { "gon", "Gondi" },
            { "got", "Gothic" },
            { "grb", "Grebo" },
            { "grc", "Greek, Ancient (to 1453)" },
            { "gre", "Greek" },
            { "grn", "Guarani" },
            { "guj", "Gujarati" },
            { "hai", "Haida" },
            { "hau", "Hausa" },
            { "haw", "Hawaiian" },
            { "heb", "Hebrew" },
            { "her", "Herero" },
            { "hil", "Hiligaynon" },
            { "him", "Himachali" },
            { "hin", "Hindi" },
            { "hmo", "Hiri Motu" },
            { "hun", "Hungarian" },
            { "hup", "Hupa" },
            { "hye", "Armenian" },
            { "iba", "Iban" },
            { "ibo", "Igbo" },
            { "ice", "Icelandic" },
            { "ijo", "Ijo" },
            { "iku", "Inuktitut" },
            { "ilo", "Iloko" },
            { "ina", "Interlingua (International Auxiliary language Association)" },
            { "inc", "Indic (Other)" },
            { "ind", "Indonesian" },
            { "ine", "Indo-European (Other) Interlingue" },
            { "ipk", "Inupiak" },
            { "ira", "Iranian (Other)" },
            { "iri", "Irish" },
            { "iro", "Iroquoian uages" },
            { "isl", "Icelandic" },
            { "ita", "Italian" },
            { "jav", "Javanese" },
            { "jaw", "Javanese" },
            { "jpn", "Japanese" },
            { "jpr", "Judeo-Persian" },
            { "jrb", "Judeo-Arabic" },
            { "kaa", "Kara-Kalpak" },
            { "kab", "Kabyle" },
            { "kac", "Kachin" },
            { "kal", "Greenlandic" },
            { "kam", "Kamba" },
            { "kan", "Kannada" },
            { "kar", "Karen" },
            { "kas", "Kashmiri" },
            { "kat", "Georgian" },
            { "kau", "Kanuri" },
            { "kaw", "Kawi" },
            { "kaz", "Kazakh" },
            { "kha", "Khasi" },
            { "khi", "Khoisan (Other)" },
            { "khm", "Khmer" },
            { "kho", "Khotanese" },
            { "kik", "Kikuyu" },
            { "kin", "Kinyarwanda" },
            { "kir", "Kirghiz" },
            { "kok", "Konkani" },
            { "kom", "Komi" },
            { "kon", "Kongo" },
            { "kor", "Korean" },
            { "kpe", "Kpelle" },
            { "kro", "Kru" },
            { "kru", "Kurukh" },
            { "kua", "Kuanyama" },
            { "kum", "Kumyk" },
            { "kur", "Kurdish" },
            { "kus", "Kusaie" },
            { "kut", "Kutenai" },
            { "lad", "Ladino" },
            { "lah", "Lahnda" },
            { "lam", "Lamba" },
            { "lao", "Lao" },
            { "lat", "Latin" },
            { "lav", "Latvian" },
            { "lez", "Lezghian" },
            { "lin", "Lingala" },
            { "lit", "Lithuanian" },
            { "lol", "Mongo" },
            { "loz", "Lozi" },
            { "ltz", "Letzeburgesch" },
            { "lub", "Luba-Katanga" },
            { "lug", "Ganda" },
            { "lui", "Luiseno" },
            { "lun", "Lunda" },
            { "luo", "Luo (Kenya and Tanzania)" },
            { "mac", "Macedonian" },
            { "mad", "Madurese" },
            { "mag", "Magahi" },
            { "mah", "Marshall" },
            { "mai", "Maithili" },
            { "mak", "Macedonian Makasar" },
            { "mal", "Malayalam" },
            { "man", "Mandingo" },
            { "mao", "Maori" },
            { "map", "Austronesian (Other)" },
            { "mar", "Marathi" },
            { "mas", "Masai" },
            { "max", "Manx" },
            { "may", "Malay" },
            { "men", "Mende" },
            { "mga", "Irish, Middle (900 - 1200)" },
            { "mic", "Micmac" },
            { "min", "Minangkabau" },
            { "mis", "Miscellaneous (Other)" },
            { "mkh", "Mon-Kmer (Other)" },
            { "mlg", "Malagasy" },
            { "mlt", "Maltese" },
            { "mni", "Manipuri" },
            { "mno", "Manobo Languages" },
            { "moh", "Mohawk" },
            { "mol", "Moldavian" },
            { "mon", "Mongolian" },
            { "mos", "Mossi" },
            { "mri", "Maori" },
            { "msa", "Malay" },
            { "mul", "Multiple Languages" },
            { "mun", "Munda Languages" },
            { "mus", "Creek" },
            { "mwr", "Marwari" },
            { "mya", "Burmese" },
            { "myn", "Mayan Languages" },
            { "nah", "Aztec" },
            { "nai", "North American Indian (Other)" },
            { "nau", "Nauru" },
            { "nav", "Navajo" },
            { "nbl", "Ndebele, South" },
            { "nde", "Ndebele, North" },
            { "ndo", "Ndongo" },
            { "nep", "Nepali" },
            { "new", "Newari" },
            { "nic", "Niger-Kordofanian (Other)" },
            { "niu", "Niuean" },
            { "nla", "Dutch" },
            { "nno", "Norwegian (Nynorsk)" },
            { "non", "Norse, Old" },
            { "nor", "Norwegian" },
            { "nso", "Sotho, Northern" },
            { "nub", "Nubian Languages" },
            { "nya", "Nyanja" },
            { "nym", "Nyamwezi" },
            { "nyn", "Nyankole" },
            { "nyo", "Nyoro" },
            { "nzi", "Nzima" },
            { "oci", "Langue d'Oc (post 1500)" },
            { "oji", "Ojibwa" },
            { "ori", "Oriya" },
            { "orm", "Oromo" },
            { "osa", "Osage" },
            { "oss", "Ossetic" },
            { "ota", "Turkish, Ottoman (1500 - 1928)" },
            { "oto", "Otomian Languages" },
            { "paa", "Papuan-Australian (Other)" },
            { "pag", "Pangasinan" },
            { "pal", "Pahlavi" },
            { "pam", "Pampanga" },
            { "pan", "Panjabi" },
            { "pap", "Papiamento" },
            { "pau", "Palauan" },
            { "peo", "Persian, Old (ca 600 - 400 B.C.)" },
            { "per", "Persian" },
            { "phn", "Phoenician" },
            { "pli", "Pali" },
            { "pol", "Polish" },
            { "pon", "Ponape" },
            { "por", "Portuguese" },
            { "pra", "Prakrit uages" },
            { "pro", "Provencal, Old (to 1500)" },
            { "pus", "Pushto" },
            { "que", "Quechua" },
            { "raj", "Rajasthani" },
            { "rar", "Rarotongan" },
            { "roa", "Romance (Other)" },
            { "roh", "Rhaeto-Romance" },
            { "rom", "Romany" },
            { "ron", "Romanian" },
            { "rum", "Romanian" },
            { "run", "Rundi" },
            { "rus", "Russian" },
            { "sad", "Sandawe" },
            { "sag", "Sango" },
            { "sah", "Yakut" },
            { "sai", "South American Indian (Other)" },
            { "sal", "Salishan Languages" },
            { "sam", "Samaritan Aramaic" },
            { "san", "Sanskrit" },
            { "sco", "Scots" },
            { "scr", "Croatian" },
            { "sel", "Selkup" },
            { "sem", "Semitic (Other)" },
            { "sga", "Irish, Old (to 900)" },
            { "shn", "Shan" },
            { "sid", "Sidamo" },
            { "sin", "Singhalese" },
            { "sio", "Siouan Languages" },
            { "sit", "Sino-Tibetan (Other)" },
            { "sla", "Slavic (Other)" },
            { "slk", "Slovak" },
            { "slo", "Slovak" },
            { "slv", "Slovenian" },
            { "smi", "Sami Languages" },
            { "smo", "Samoan" },
            { "sna", "Shona" },
            { "snd", "Sindhi" },
            { "sog", "Sogdian" },
            { "som", "Somali" },
            { "son", "Songhai" },
            { "sot", "Sotho, Southern" },
            { "spa", "Spanish" },
            { "sqi", "Albanian" },
            { "srd", "Sardinian" },
            { "srr", "Serer" },
            { "ssa", "Nilo-Saharan (Other)" },
            { "ssw", "Siswant Swazi" },
            { "suk", "Sukuma" },
            { "sun", "Sudanese" },
            { "sus", "Susu" },
            { "sux", "Sumerian" },
            { "sve", "Swedish" },
            { "swa", "Swahili" },
            { "swe", "Swedish" },
            { "syr", "Syriac" },
            { "tah", "Tahitian" },
            { "tam", "Tamil" },
            { "tat", "Tatar" },
            { "tel", "Telugu" },
            { "tem", "Timne" },
            { "ter", "Tereno" },
            { "tgk", "Tajik" },
            { "tgl", "Tagalog" },
            { "tha", "Thai" },
            { "tib", "Tibetan" },
            { "tig", "Tigre" },
            { "tir", "Tigrinya" },
            { "tiv", "Tivi" },
            { "tli", "Tlingit" },
            { "tmh", "Tamashek" },
            { "tog", "Tonga (Nyasa)" },
            { "ton", "Tonga (Tonga Islands)" },
            { "tru", "Truk" },
            { "tsi", "Tsimshian" },
            { "tsn", "Tswana" },
            { "tso", "Tsonga" },
            { "tuk", "Turkmen" },
            { "tum", "Tumbuka" },
            { "tur", "Turkish" },
            { "tut", "Altaic (Other)" },
            { "twi", "Twi" },
            { "tyv", "Tuvinian" },
            { "uga", "Ugaritic" },
            { "uig", "Uighur" },
            { "ukr", "Ukrainian" },
            { "umb", "Umbundu" },
            { "und", "Undetermined" },
            { "urd", "Urdu" },
            { "uzb", "Uzbek" },
            { "vai", "Vai" },
            { "ven", "Venda" },
            { "vie", "Vietnamese" },
            { "vol", "Volapük" },
            { "vot", "Votic" },
            { "wak", "Wakashan Languages" },
            { "wal", "Walamo" },
            { "war", "Waray" },
            { "was", "Washo" },
            { "wel", "Welsh" },
            { "wen", "Sorbian Languages" },
            { "wol", "Wolof" },
            { "xho", "Xhosa" },
            { "yao", "Yao" },
            { "yap", "Yap" },
            { "yid", "Yiddish" },
            { "yor", "Yoruba" },
            { "zap", "Zapotec" },
            { "zen", "Zenaga" },
            { "zha", "Zhuang" },
            { "zho", "Chinese" },
            { "zul", "Zulu" },
            { "zun", "Zuni" },
            { "tkl", "Tokelau" },
            { "hrv", "Croatian" },
            { "bos", "Bosnian" },
            { "scc", "Serbian" },
            { "srp", "Serbian" }
            #endregion <<< Language code / English description dictionary
        };

        /// <summary>
        /// Gets a string array of the English version of the language names sorted alphabetically.
        /// </summary>
        /// <value>A string array of the English version of the language names sorted alphabetically.</value>
        public static string[] SortedLanguages { get; } = [
            #region <<< Sorted languages >>>
            "Abkhazian",
             "Achinese",
             "Acoli",
             "Adangme",
             "Afar",
             "Afrihili",
             "Afrikaans",
             "Afro-Asiatic (Other)",
             "Akan",
             "Akkadian",
             "Albanian",
             "Aleut",
             "Algonquian Languages",
             "Altaic (Other)",
             "Amharic",
             "Apache Languages",
             "Arabic",
             "Aramaic",
             "Arapaho",
             "Araucanian",
             "Arawak",
             "Armenian",
             "Artificial (Other)",
             "Assamese",
             "Athapascan Languages",
             "Austronesian (Other)",
             "Avaric",
             "Avestan",
             "Awadhi",
             "Aymara",
             "Azerbaijani",
             "Aztec",
             "Balinese",
             "Baltic (Other)",
             "Baluchi",
             "Bambara",
             "Bamileke Languages",
             "Banda",
             "Bantu (Other)",
             "Basa",
             "Bashkir",
             "Basque",
             "Beja",
             "Bemba",
             "Bengali",
             "Berber (Other)",
             "Bhojpuri",
             "Bihari",
             "Bikol",
             "Bini",
             "Bislama",
             "Bosnian",
             "Braj",
             "Breton",
             "Buginese",
             "Bulgarian",
             "Buriat",
             "Burmese",
             "Byelorussian",
             "Caddo",
             "Carib",
             "Catalan",
             "Caucasian (Other)",
             "Cebuano",
             "Celtic (Other)",
             "Central American Indian (Other)",
             "Chagatai",
             "Chamorro",
             "Chechen",
             "Cherokee",
             "Cheyenne",
             "Chibcha",
             "Chinese",
             "Chinook jargon",
             "Choctaw",
             "Church Slavic",
             "Chuvash",
             "Coptic",
             "Cornish",
             "Corsican",
             "Cree",
             "Creek",
             "Creoles and Pidgins (Other)",
             "Creoles and Pidgins, English-based (Other)",
             "Creoles and Pidgins, French-based (Other)",
             "Creoles and Pidgins, Portuguese-based (Other)",
             "Croatian",
             "Cushitic (Other)",
             "Czech",
             "Dakota",
             "Danish",
             "Delaware",
             "Dinka",
             "Divehi",
             "Dogri",
             "Dravidian (Other)",
             "Duala",
             "Dutch",
             "Dutch, Middle (ca. 1050-1350)",
             "Dyula",
             "Dzongkha",
             "Efik",
             "Egyptian (Ancient)",
             "Ekajuk",
             "Elamite",
             "English",
             "English, Old (ca. 450-1100)",
             "Eskimo (Other)",
             "Esperanto",
             "Estonian",
             "Ewe",
             "Ewondo",
             "Fang",
             "Fanti",
             "Faroese",
             "Fijian",
             "Finnish",
             "Finno-Ugrian (Other)",
             "Fon",
             "French",
             "French, Middle (ca. 1400-1600)",
             "French, Old (842- ca. 1400)",
             "Frisian",
             "Fulah",
             "Ga",
             "Gaelic (Scots)",
             "Gallegan",
             "Ganda",
             "Gayo",
             "Geez",
             "Georgian",
             "German",
             "German, Middle High (ca. 1050-1500)",
             "German, Old High (ca. 750-1050)",
             "Germanic (Other)",
             "Gilbertese",
             "Gondi",
             "Gothic",
             "Grebo",
             "Greek",
             "Greek, Ancient (to 1453)",
             "Greenlandic",
             "Guarani",
             "Gujarati",
             "Haida",
             "Hausa",
             "Hawaiian",
             "Hebrew",
             "Herero",
             "Hiligaynon",
             "Himachali",
             "Hindi",
             "Hiri Motu",
             "Hungarian",
             "Hupa",
             "Iban",
             "Icelandic",
             "Igbo",
             "Ijo",
             "Iloko",
             "Indic (Other)",
             "Indo-European (Other) Interlingue",
             "Indonesian",
             "Interlingua (International Auxiliary language Association)",
             "Inuktitut",
             "Inupiak",
             "Iranian (Other)",
             "Irish",
             "Irish, Middle (900 - 1200)",
             "Irish, Old (to 900)",
             "Iroquoian uages",
             "Italian",
             "Japanese",
             "Javanese",
             "Judeo-Arabic",
             "Judeo-Persian",
             "Kabyle",
             "Kachin",
             "Kamba",
             "Kannada",
             "Kanuri",
             "Kara-Kalpak",
             "Karen",
             "Kashmiri",
             "Kawi",
             "Kazakh",
             "Khasi",
             "Khmer",
             "Khoisan (Other)",
             "Khotanese",
             "Kikuyu",
             "Kinyarwanda",
             "Kirghiz",
             "Komi",
             "Kongo",
             "Konkani",
             "Korean",
             "Kpelle",
             "Kru",
             "Kuanyama",
             "Kumyk",
             "Kurdish",
             "Kurukh",
             "Kusaie",
             "Kutenai",
             "Ladino",
             "Lahnda",
             "Lamba",
             "Langue d'Oc (post 1500)",
             "Lao",
             "Latin",
             "Latvian",
             "Letzeburgesch",
             "Lezghian",
             "Lingala",
             "Lithuanian",
             "Lozi",
             "Luba-Katanga",
             "Luiseno",
             "Lunda",
             "Luo (Kenya and Tanzania)",
             "Macedonian",
             "Macedonian Makasar",
             "Madurese",
             "Magahi",
             "Maithili",
             "Malagasy",
             "Malay",
             "Malayalam",
             "Maltese",
             "Mandingo",
             "Manipuri",
             "Manobo Languages",
             "Manx",
             "Maori",
             "Marathi",
             "Mari",
             "Marshall",
             "Marwari",
             "Masai",
             "Mayan Languages",
             "Mende",
             "Micmac",
             "Middle English (ca. 1100-1500)",
             "Minangkabau",
             "Miscellaneous (Other)",
             "Mohawk",
             "Moldavian",
             "Mongo",
             "Mongolian",
             "Mon-Kmer (Other)",
             "Mossi",
             "Multiple Languages",
             "Munda Languages",
             "Nauru",
             "Navajo",
             "Ndebele, North",
             "Ndebele, South",
             "Ndongo",
             "Nepali",
             "Newari",
             "Niger-Kordofanian (Other)",
             "Nilo-Saharan (Other)",
             "Niuean",
             "Norse, Old",
             "North American Indian (Other)",
             "Norwegian",
             "Norwegian (Nynorsk)",
             "Nubian Languages",
             "Nyamwezi",
             "Nyanja",
             "Nyankole",
             "Nyoro",
             "Nzima",
             "Ojibwa",
             "Oriya",
             "Oromo",
             "Osage",
             "Ossetic",
             "Otomian Languages",
             "Pahlavi",
             "Palauan",
             "Pali",
             "Pampanga",
             "Pangasinan",
             "Panjabi",
             "Papiamento",
             "Papuan-Australian (Other)",
             "Persian",
             "Persian, Old (ca 600 - 400 B.C.)",
             "Phoenician",
             "Polish",
             "Ponape",
             "Portuguese",
             "Prakrit uages",
             "Provencal, Old (to 1500)",
             "Pushto",
             "Quechua",
             "Rajasthani",
             "Rarotongan",
             "Rhaeto-Romance",
             "Romance (Other)",
             "Romanian",
             "Romany",
             "Rundi",
             "Russian",
             "Salishan Languages",
             "Samaritan Aramaic",
             "Sami Languages",
             "Samoan",
             "Sandawe",
             "Sango",
             "Sanskrit",
             "Sardinian",
             "Scots",
             "Selkup",
             "Semitic (Other)",
             "Serbian",
             "Serer",
             "Shan",
             "Shona",
             "Sidamo",
             "Siksika",
             "Sindhi",
             "Singhalese",
             "Sino-Tibetan (Other)",
             "Siouan Languages",
             "Siswant Swazi",
             "Slavic (Other)",
             "Slovak",
             "Slovenian",
             "Sogdian",
             "Somali",
             "Songhai",
             "Sorbian Languages",
             "Sotho, Northern",
             "Sotho, Southern",
             "South American Indian (Other)",
             "Spanish",
             "Sudanese",
             "Sukuma",
             "Sumerian",
             "Susu",
             "Swahili",
             "Swedish",
             "Syriac",
             "Tagalog",
             "Tahitian",
             "Tajik",
             "Tamashek",
             "Tamil",
             "Tatar",
             "Telugu",
             "Tereno",
             "Thai",
             "Tibetan",
             "Tigre",
             "Tigrinya",
             "Timne",
             "Tivi",
             "Tlingit",
             "Tokelau",
             "Tonga (Nyasa)",
             "Tonga (Tonga Islands)",
             "Truk",
             "Tsimshian",
             "Tsonga",
             "Tswana",
             "Tumbuka",
             "Turkish",
             "Turkish, Ottoman (1500 - 1928)",
             "Turkmen",
             "Tuvinian",
             "Twi",
             "Ugaritic",
             "Uighur",
             "Ukrainian",
             "Umbundu",
             "Undetermined",
             "Urdu",
             "Uzbek",
             "Vai",
             "Venda",
             "Vietnamese",
             "Volapük",
             "Votic",
             "Wakashan Languages",
             "Walamo",
             "Waray",
             "Washo",
             "Welsh",
             "Wolof",
             "Xhosa",
             "Yakut",
             "Yao",
             "Yap",
             "Yiddish",
             "Yoruba",
             "Zapotec",
             "Zenaga",
             "Zhuang",
             "Zulu",
             "Zuni"
            #endregion <<< Sorted languages >>>
        ];
    }
}
